"""Add avatar and dark_mode to User

Revision ID: 8ebed9d3feba
Revises: 094c15a4fe70
Create Date: 2026-05-26 15:06:05.147611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebed9d3feba'
down_revision = '094c15a4fe70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
      batch_op.add_column(sa.Column('avatar_image', sa.String(length=255), nullable=False, server_default='default.png'))
      batch_op.add_column(sa.Column('dark_mode', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dark_mode')
        batch_op.drop_column('avatar_image')

    # ### end Alembic commands ###
